name: Jaroslav Lobačevski
description:
meta_description: "Jaroslav Lobačevski"
future: true
markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
google_analytics: 'UA-136416829-1'
plugins: [jekyll-paginate]
url: https://blog.devsecurity.eu
baseurl: "/"
author: 'Jaroslav Lobačevski'
about: 'about.html'
